//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistMovimientosSIAS
    {
        public long idHistMovimientoSIAS { get; set; }
        public int idEmpresa { get; set; }
        public int idEmpresaInfFiscal { get; set; }
        public string cusId { get; set; }
        public int idClub { get; set; }
        public int idPlan { get; set; }
        public int idFormato { get; set; }
        public int idNivel { get; set; }
        public int idTipoPago { get; set; }
        public string afectacionContable { get; set; }
        public string cuentaContable { get; set; }
        public string concepto { get; set; }
        public Nullable<decimal> cargo { get; set; }
        public Nullable<decimal> abono { get; set; }
        public string modulo { get; set; }
        public string tipoMovimiento { get; set; }
        public System.DateTime fechaMovimiento { get; set; }
        public System.DateTime fechaInsert { get; set; }
        public string usuarioInsert { get; set; }
        public Nullable<System.DateTime> fechaUpdate { get; set; }
        public string usuarioUpdate { get; set; }
    }
}
