//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanEmpresa
    {
        public int idEmpresa { get; set; }
        public int idEmpresaInfFiscal { get; set; }
        public int idPlan { get; set; }
        public decimal porcPagoCia { get; set; }
        public decimal porcPagoNomina { get; set; }
        public decimal porcPagoEmpleado { get; set; }
        public long numSocios { get; set; }
        public bool estatus { get; set; }
        public System.DateTime fechaInsert { get; set; }
        public string usuarioInsert { get; set; }
        public Nullable<System.DateTime> fechaUpdate { get; set; }
        public string usuarioUpdate { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual PlanEmpresa PlanEmpresa1 { get; set; }
        public virtual PlanEmpresa PlanEmpresa2 { get; set; }
    }
}
